version: "3.8"

services:

  rq-dashboard:
    image: ucyo/rq-dashboard:latest
    init: true
    env_file:
      - ./env/.rq.env
    depends_on:
      - redis
      - worker

  redis:
    image: redis:5
    init: true

  worker:
    init: true
    image: code
    env_file:
      - ./env/.rq.env
      - ./env/.cdsapirc.env
    command: /bin/bash -c "wait-for-it -s -t 60 redis:6379 && envsubst '$$API_KEY $$UID $$VERIFY' < /code/cdsapirc.template > /root/.cdsapirc && rq worker --url redis://redis:6379"
    depends_on:
      - redis

  code:
    init: true
    build:
      context: ./code
      dockerfile: Dockerfile
    image: code
    env_file:
      - ./env/.rq.env
      - ./env/.cdsapirc.env
    command: /bin/bash -c "wait-for-it -s -t 60 redis:6379 && envsubst '$$API_KEY $$UID $$VERIFY' < /code/cdsapirc.template > /root/.cdsapirc && tail -F /dev/null"
    depends_on:
      - redis
      - worker
