version: "3.8"

services:

  rq-dashboard:
    ports:
      - "9181:9181"

  redis:
    volumes:
      - ./code/rstore:/data

  code:
    volumes:
      - ./code:/home/python/code
      - /mnt/raid6/abcde:/abcde
      - /abcde:/abcde_test

  worker:
    volumes:
      - ./code:/home/python/code
      - /mnt/raid6/abcde:/abcde
      - /abcde:/abcde_test
