version: "3.8"

services:
  code:
    build:
      context: ./code
      dockerfile: Dockerfile
    env_file:
      - ./env/.jupyter.env
      - ./env/.cdsapirc.env
    command: /bin/bash -c "envsubst '$$API_KEY $$UID $$VERIFY' < /home/python/code/cdsapirc.template > /home/python/.cdsapirc && jupyter notebook --config=/home/python/code/jupyter_notebook_config.py"
