version: "3.8"

services:

  redis:
    volumes:
      - ./code/rstore:/data

  code:
    volumes:
      - ./code:/home/python/code
      - ./downloads:/downloads
    ports:
      - "9181:9181"

  worker:
    volumes:
      - ./code:/home/python/code
      - ./downloads:/downloads
